### ISSUE TITLE
Commit activity grid not rendered correctly

### ISSUE THREAD

**Issue by 2ion** [synthtech/github-mod#1]
When using the style with Firefox 40beta7, the commit activity grid remains white in most parts but each tile of the grid will be rendered after having moved the mouse over it.

Initial state:

![2015-07-25-211517_969x380_scrot](https://cloud.githubusercontent.com/assets/666784/8890909/89e77dda-3312-11e5-978b-5c414900c610.png)

After some mouse-moving:

![2015-07-25-211739_972x390_scrot](https://cloud.githubusercontent.com/assets/666784/8890911/a059fd2c-3312-11e5-8ab0-4d12d1ee3d06.png)

**Comment by synthtech** [comment]
I couldn't reproduce this using Firefox 41b1 or Waterfox 39.

Does it only happen when the userstyle is enabled?

**Comment by 2ion** [comment]
You are right, the problem doesn't occur in Nightly or Beta anymore. It seems like it was a short-lived Firefox (or maybe graphics stack) bug; when for example scrolling code views horizontally, the text would be completely distorted (now also fixed).

So I'm closing this now. Thanks for following up!
