### ISSUE TITLE
New label color picker's z-index issue

### ISSUE THREAD

**Issue by katabamia** [synthtech/github-mod#10]
Hello synthtech, I found little z-index issue while using your style.

In labels creating page, new label color picker will shown above of header.
(See attached image, its very quick to understand.)

![image](https://cloud.githubusercontent.com/assets/9818101/26516238/edaafa24-42bd-11e7-9490-e6146673afe5.png)

**Comment by synthtech** [comment]
Should be fixed in 6e3d200

**Comment by katabamia** [comment]
Seems fixed perfectly. Thanks for great work!
