### ISSUE TITLE
Some issue at Organization page

### ISSUE THREAD

**Issue by katabamia** [synthtech/github-mod#11]
Hello again, synthtech.

I found some bugs at Org page.

1: Organization visibility popup at `https://github.com/orgs/{OrgName}/people`
when hover popup items, I think strong string color should be changed to white. (e.g. Public/Private)
![image](https://user-images.githubusercontent.com/9818101/27660977-786173de-5c93-11e7-99fa-52477bf3eb18.png)

2: List items and account dropdown at `https://github.com/orgs/{OrgName}/people` and `https://github.com/orgs/{OrgName}/teams`
List items and account dropdown has z-index issue.
![image](https://user-images.githubusercontent.com/9818101/27661126-2211bed4-5c94-11e7-9160-3dede45f1d01.png)
![image](https://user-images.githubusercontent.com/9818101/27661135-2b8c9330-5c94-11e7-9511-066836d8404c.png)

**Comment by synthtech** [comment]
Fixed in 2684081 and 10a9ec3

**Comment by katabamia** [comment]
Seems fixed perfectly! Big thanks!
