### ISSUE TITLE
Negative margin issue at profile page

### ISSUE THREAD

**Issue by katabame** [synthtech/github-mod#12]
Hello again, synthtech.

when update the profile info, banner will shown at top of the page.
but it's little shifting to down.

![image](https://user-images.githubusercontent.com/9818101/28756851-940c70f2-75b1-11e7-930a-68f5869f35f5.png)

**Comment by synthtech** [comment]
Fixed in 62961bf

**Comment by katabame** [comment]
Always so quickly and awesome, thank you so much!!
