### ISSUE TITLE
Font: 'Open Sans' doesn't work

### ISSUE THREAD

**Issue by demidovakatya** [synthtech/github-mod#4]
I installed the Github Mod style to find out it's Times New Roman everywhere:

![](https://cloud.githubusercontent.com/assets/5788652/12686591/90516cf0-c6db-11e5-9ce8-52e1721b6ea6.png)

If I add `sans-serif` to the style or comment out the line with `font-family: 'Open Sans' !important;`, things turn back to normal.

I'm talking about this line:

![i 2016-01-29 at 23 02 03](https://cloud.githubusercontent.com/assets/5788652/12686825/1898fbc2-c6dd-11e5-8a59-98dba4642094.png)

**Comment by synthtech** [comment]
I just updated the style now, adding in `sans-serif`.

I think something might be blocking the retrieval of the webfont for it to break like that.

**Comment by demidovakatya** [comment]
Thanks, it works now. :+1:

**Comment by demidovakatya** [comment]
> I think something might be blocking the retrieval of the webfont for it to break like that.

But the Open Sans font still doesn't work, so I'm not closing the issue, ok?

**Comment by demidovakatya** [comment]
Oh, I've just noticed this in my developer's tools:

> [Error] Refused to load the font 'https://fonts.gstatic.com/s/opensans/v13/u-WUoqrET9fUeobQW7jkRT8E0i7KZn-EPnyo3HZu7kw.woff' because it violates the following Content Security Policy directive: "font-src assets-cdn.github.com".
> [Error] Refused to load the font 'https://fonts.gstatic.com/s/opensans/v13/xjAJXh38I15wypJXxuGMBtIh4imgI8P11RFo6YPCPC0.woff' because it violates the following Content Security Policy directive: "font-src assets-cdn.github.com".

After a quick research, I found [this](http://www.w3.org/TR/CSP/#directive-font-src):

> The font-src directive restricts from where the protected resource can load fonts. The syntax for the name and value of the directive are described by the following ABNF grammar:
> 
> directive-name    = "font-src"
> directive-value   = source-list
> The term allowed font sources refers to the result of parsing the font-src directive’s value as a source list if the policy contains an explicit font-src, or otherwise to the default sources.
> 
> Whenever the user agent fetches a URL in the course of one of the following activities, if the URL does not match the allowed font sources for the protected resource, the user agent MUST act as if there was a fatal network error and no resource was obtained, and report a violation:
> 
> Requesting data for display in a font, such as when processing the <<@font-face>> Cascading Style Sheets (CSS) rule.

**Comment by synthtech** [comment]
What browser are you using?

On Chromium, Stylish seems to be bypassing the CSP by injecting it into the page's JS or something like that. (I'm not really sure) 
![](https://puu.sh/mPIzK/bf9f94ac93.png)

**Comment by demidovakatya** [comment]
Safari.

**Comment by synthtech** [comment]
It could be a problem with the Stylish extension for Safari specifically, as it works fine for me in Firefox as well.

> I'm totally fine without Open Sans

Alright, well I'd still like to keep the userstyle consistent across browsers, if possible :smile:

**Comment by demidovakatya** [comment]
Could you have a look at this issue? I didn't get what they were talking about, but I think it might be related to our problem.

https://github.com/350d/stylish/issues/7

**Comment by synthtech** [comment]
I don't think the issue is related. They mention that the extension UI wasn't working for them.
