### ISSUE TITLE
wrong floating headers z-index.

### ISSUE THREAD

**Issue by h404bi** [synthtech/github-mod#6]
![20160806132346](https://cloud.githubusercontent.com/assets/5764917/17454897/6a38b896-5bd9-11e6-8c54-d2bd48cf20b7.png)
![20160806132915](https://cloud.githubusercontent.com/assets/5764917/17454907/cc6f40e8-5bd9-11e6-9365-9bec45872211.png)

maybe we should tweak the z-index value of header.

**Comment by synthtech** [comment]
a3a5d11 should fix this.

**Comment by h404bi** [comment]
you rock! :+1:
