### ISSUE TITLE
seems that there are excessive white space between header and body

### ISSUE THREAD

**Issue by h404bi** [synthtech/github-mod#9]
![20170211113715](https://cloud.githubusercontent.com/assets/5764917/22850932/b21c648c-f04e-11e6-9b52-c2a0d6890f28.png)

![20170211114600](https://cloud.githubusercontent.com/assets/5764917/22850962/aedd3566-f04f-11e6-929b-f1a47e6f7b2b.png)

**Comment by h404bi** [comment]
previous pr #7 by @matankb

**Comment by synthtech** [comment]
b713042 should fix it
